### ISSUE TITLE
Parenthesis

### ISSUE THREAD

**Issue by kdnfgc** [pguerin3/halmak4windows#1]
On the original Halmak layout, the ( ) symbols are in the center of the keyboard. On this version, however, the < > symbols are in the center. Please address this issue as soon as possible.

**Comment by pguerin3** [comment]
Thanks for the heads up.
If you inspect the original Halmak repo, it looks like the centre is different depending on which file you're using.
See the following:
https://github.com/MadRabbit/halmak/blob/master/integrations/typefu/Halmak.tfl

I will add another Windows version that swaps the <> and ().
Then typists can choose which is right for them.

**Comment by pguerin3** [comment]
Many versions have been added now.

**Comment by kdnfgc** [comment]
Out of curiousity, will you also do the same with the Linux version?

**Comment by pguerin3** [comment]
There are 2 Halmak versions for X.org in this post:
https://github.com/MadRabbit/halmak/issues/22

Simply add the text to the symbols/us file in the X.org directory for your distribution.
